id: jiusi-webserviceproxy-xxe

info:
  name: jiusi WebServiceProxy - XXE
  author: yichen
  severity: critical
  description: |
     /jsoa/WebServiceProxy 接口处存在XML实体注入漏洞，未经身份认证的攻击者可利用此漏洞获取服务器内部敏感数据，使系统处于极不安全状态。
  reference:
    - https://blog.csdn.net/qq_41904294/article/details/141227990?spm=1001.2014.3001.5502
  verified: true
  max-request: 1
  fofa-query: body="/jsoa/login.jsp"
  tags: rce


http:
- raw:
  - |+
    @timeout: 30s
    POST /jsoa/WebServiceProxy HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
    Accept: */*
    Accept-Encoding: gzip, deflate, br
    Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
    Content-Type: application/x-www-form-urlencoded
    Connection: close

  matchers:
    - type: dsl
      dsl:
        - len(body) == 0
        - status_code == 200